### ISSUE TITLE
A little confused about the  "Collection-level codegen"

### ISSUE THREAD

**Issue by ttzztztz** [postmanlabs/gsoc#1]
I am a little confused about the "Collection-level codegen".

Should I simply get all requests from an array of requests and come up with some ways to combine those outputs to one or sequences of associated files?

Looking forward to your reply.
Thank you.

**Comment by ankit-m** [comment]
@abhijitkane @umeshp7 could you add some details here?

**Comment by pandyamarut** [comment]
@ankit-m Want elaboration on same. Thanks.

**Comment by umeshp7** [comment]
Hi everyone, Thanks for the interest. 
There are various aspects to a collection:
- Requests
- Folder structure
- Collection and Environment Variables
- Pre-request and test scripts (to be ignored for now). 
- Authorization

A collection-level code, should take in consideration all of the above entities. The generated code should act as a client SDK of the collection. The behaviour of the code should be the same as the  collection. We will be ignoring the pre-request and test scripts for now. 
It is not just an array of code-snippets. The folder structure should also be maintained and we want to be able to programmatically and systematically access any request. i.e. `collection.folder.request([inputs])` for example. The process of generating this code should be language agnostic as far as possible. 

We'd have a separate repository for this with `postman-code-generators` as its dependency.

**Comment by ttzztztz** [comment]
@umeshp7 Thank you for your reply. 

Does the `collection-level codegen` allow to use the technologies like Typescript which will make it easier to maintain in the future ?

**Comment by umeshp7** [comment]
@ttzztztz 
You can use Typescript. You are free to use any language that allows easy publish on npm.

**Comment by ttzztztz** [comment]
@umeshp7 

Hello. I found a repo [postmanlabs/postman-collection](https://github.com/postmanlabs/postman-collection)

Is there any relationship between the proposal `collection-level codegen` and this repo ?
Or am I expected to create a whole new repo and implement the features in the new repo?

Looking forward to your reply.

**Comment by umeshp7** [comment]
@ttzztztz As mentioned earlier. 
We are planning to have a separate repository for this. Which will have `postman-collection` and `postman-code-generators` as dependencies. 
The input will be a postman collection which will have to be converted to an SDK. 

If you take a look at the the postman-code-generators repo, it takes in a single request of a postman-collection as input and outputs a code snippet for that request for a chosen language. Similarly, we want for this project the input will be a `postman-collection` and the output will be a collection level SDK for a specific language.

**Comment by sastava007** [comment]
@umeshp7 Sir how do we set the`headers` before making a codegen request because the collection that we export from Postman does not contain any headers as they are using `temporary-headers` which are generated by Postman and not available outside the app with collection data. 

Or if there is any way to export the temporary-headers along with other data in the collection?

**Comment by sastava007** [comment]
@ankit-m Sir, can you please clarify who'll be mentoring the Code Generator project?
As I have some project related doubts so it would be better if I directly approach them.

**Comment by umeshp7** [comment]
@sastava007 
You can consider the collection JSON to be the source of truth. Whatever information you get from that you will have to try to use that and generate the code. 

If the collection is returning an empty headers, so empty headers it is. If there is any disparity between the APP <> Collection, that is not in the scope of this project. As far as this project is considered it doesn't know anything about the App. All it knows is the collection json that you input in it. 

Moreover, the temporary headers construct is soon going to be completely removed from the app too.

**Comment by sastava007** [comment]
@umeshp7 Can I assume that we are getting the collection JSON following the v2.1 schema or do we have to also deal with v1 & v2.0?
