### ISSUE TITLE
Query in idea of implementation "newman login" feature 

### ISSUE THREAD

**Issue by Parth910** [postmanlabs/gsoc#10]
Hello,
I am a little bit confused about this idea. In the development of this feature, we have to use postman login credentials or we can use any cloud credentials for implementing this feature.
Thank you.

**Comment by ankit-m** [comment]
@codenirvana can you clarify this?

**Comment by codenirvana** [comment]
@Parth910 Newman login should leverage the Postman API Key as mentioned in the [Newman docs](https://github.com/postmanlabs/newman#using-newman-with-the-postman-api).

The idea is, once logged in, the subsequent Newman commands don't require the key in the resource's query param or `--postman-api-key` option.

**Comment by Parth910** [comment]
@codenirvana  @ankit-m  Thank you
can I submit a draft proposal for this idea and can you review it?

**Comment by codenirvana** [comment]
@Parth910 Sure 👍 
Also, refer https://github.com/postmanlabs/gsoc/issues/19#issuecomment-600409765

**Comment by Parth910** [comment]
@codenirvana thank you.
Can we include a detailed implementation of more than one feature(Mention in GSoC 2020 Newman project Ideas) in the proposal?

**Comment by ankit-m** [comment]
@Parth910 your call. But make sure that the timelines are achievable.
