### ISSUE TITLE
GSoC 2020 - Idea - Arduino Code Snippet Generation

### ISSUE THREAD

**Issue by tirtawr** [postmanlabs/gsoc#11]
Hi! I'm Tirta currently a grad student at New York University's Interactive Telecommunications Program (ITP). Previously I was a software engineer working mainly with Ruby, Java, and Javascript.

Here in my grad program, we do a lot of physical computing with Arduinos. Adding an Arduino code snippet generation would be a tremendous help to the community. I would like to propose this idea for the Google Summer of Code 2020. Would you guys be interested in something like this? Or would you rather have us (me) propose things that are more requestion (like axios code generation for example)

looking forward to hearing back from you guys :)

**Comment by ankit-m** [comment]
Definitely! We are more than happy to consider proposals on original ideas. However, do ensure that the project is detailed enough to warrant a 3-month timeline.
