### ISSUE TITLE
Need help regarding GSoC 2020

### ISSUE THREAD

**Issue by gittysachin** [postmanlabs/gsoc#12]
Hi,

I’m Sachin Jangid, a pre-final year student pursuing Computer Science at the University College of Engineering & Technology, Bikaner. I have worked in the Software Engineering domain for more than 1 year now. I’ve previously worked part-time as a Remote Software Engineer at iLocalBox, a healthcare startup in California, to make software solutions for patients that can impact their lives in a very good way.
I’ve been an active open source contributor. I found out Postman as a very cool and active community who’s doing great work. I would love to be a part of Postman in the GSOC program. I’m interested in **newman**, hence I would like to contribute to it and apply for the same under GSoC.

I’ve used the app and built it on my machine. It’s working fine. I’ll try my best to contribute to newman. But I think it's late to get started now. I tried to reach out to your team and mentors in the IRC channel but it doesn't seem to work. There are many others out who have made many more PRs and solve many issues. So please let me know if there are any chances for me to getting selected. 

Please let me know if you have any suggestions :blush:.
Thank you.

**Comment by gittysachin** [comment]
@codenirvana @shamasis please guide me.

**Comment by ankit-m** [comment]
@gittysachin it is okay to get started right now. Try to resolve some user reported issues to familiarize yourself with the codebase. You can then submit a proposal for one of the ideas.
