### ISSUE TITLE
I am not able to find the IRC channel?

### ISSUE THREAD

**Issue by KKghub** [postmanlabs/gsoc#13]

**Comment by KKghub** [comment]
In the Readme.md it is written that IRC link is chat.freenode.net which I am not able to open..
Then I tried google search and found out https://webchat.freenode.net/ where I put "#postman-gsoc" as the channel. I am wondering whether I am doing the right thing since after opening the channel I don't see any messages. 17 participants are there but no messages. Could you guide me regarding this...

**Comment by jimc404** [comment]
You are on the right track. In IRC the messages are not stored anywhere so you have to use a client if you want their log. Freenode's webchat is good for quick conversations, but if you want to hang around then use some other service or configure a client on your system. Here are some links to get you started with IRC:

- [Beginner’s guide to IRC](https://fedoramagazine.org/beginners-guide-irc/) 
- [Getting started with IRC](https://opensource.com/article/16/6/getting-started-irc) 
- [An IRC quickstart guide](https://opensource.com/article/16/6/irc-quickstart-guide)

**Comment by KKghub** [comment]
Thanks for the response. I have installed Hexchat IRC and able to connect using it but I don't see any activity on the channel. Is it active at all? I'd raise issue here or directly mail rather than chatting I believe to get help.

**Comment by jimc404** [comment]
IRC etiquette is that you don't even need to introduce yourself and you can lurk around as long as you want. So it's common to have no significant activity (also most of the online users may not be there, it's just their client logging the messages) 

If you want to talk you can introduce yourself and start a conversation.
