### ISSUE TITLE
Query regarding Newman Project and Proposal

### ISSUE THREAD

**Issue by shubhamjadon** [postmanlabs/gsoc#17]
Hello, I have following queries:

1. I wanted to contribute to Newman project and found issue #2117 which was not assigned to anyone and i applied to claim that issue(6 days ago) but it has not been assigned to me yet. I have implemented it locally and it is working fine . So, should i start a pull request and mention that pull request in proposals other information section.
2. Should i also mention issue that i solved in proposal but for that issue i did not implemented a new feature or solved a bug as that issue was a form of #2117(mentioned above) and the contributor needed that feature in hurry so i provided him necessary code and guided him how he can implement it in his local Newman library.
3. I have developed sample or partial implementation of the idea (Ability to execute individual request) and have provided it in code samples also I have provided link to output of sample run(which was in form of a video), so should i also include screenshots of that output in proposal.

Thank You

**Comment by codenirvana** [comment]
Hey @shubhamjadon, you can raise the PR in Newman which implements the feature mentioned in #2117.
