### ISSUE TITLE
Query regarding gsoc terms

### ISSUE THREAD

**Issue by tirtawr** [postmanlabs/gsoc#18]
Hi,

So I'm currently writing up a proposal for Arduino code snippet generation from a Postman request. I'm a little bit confused about whether or not I should include the integration of the code generation into the main electron Postman app, given the fact that the app itself is not open source. (or is it open source? because I cant seem to find it in any of the public repos)

Looking forward to hearing back from you 😄

**Comment by ankit-m** [comment]
Integration in our electron app is not required.
