### ISSUE TITLE
Create 2021.md

### ISSUE THREAD

**Issue by ShubhamPalriwala** [postmanlabs/gsoc#24]
As of now, the 2021 project ideas are only on a [google doc](https://docs.google.com/document/d/1F2RWY7wmexsv5KOPsH7T_XiITt8gDK1PPPoaCFf5Ua8/edit)!
In my opinion, since you already have a repo with respect to GSOC, having a 2021 folder with all the necessary details will help fellow participants!

**Comment by Sharath-Postman** [comment]
Updated
