### ISSUE TITLE
Single Request Functionality and Parallel Iterations

### ISSUE THREAD

**Issue by adityaofficial10** [postmanlabs/gsoc#25]
This is to inform you that I have compiled and formulated my ideas into my proposal which would benefit greatly by your valuable feedback.
Kindly review it.
https://docs.google.com/document/d/1gFQpCDwde_uD8f0sl4Qk8jLBbkJKRIegQtto-4AZF4g/edit?usp=sharing

**Comment by Sharath-Postman** [comment]
@adityaofficial10 
Thank you for submitting and we will look into this at the earliest but as mentioned in the guidelines on discourse, for your own benefit please discuss your idea on the discourse group with the mentors before going ahead and submitting your proposal directly here. 

If you're still confident that this is your proposal, then request your patience.

Please don't tag anyone from postman while creating the issue. Request if you can update this one or create a new one post reading the next line

Do let me know if you would like more time to discuss, get this reviewed with mentors on discourse.

Cheers

**Comment by adityaofficial10** [comment]
@Sharath-Postman 
Sorry for the violations.
I just misinterpreted it I think.
I will do the needful but please try to have a look if possible.
Thanks again for your help.

**Comment by Sharath-Postman** [comment]
@adityaofficial10 I will request the team to look into it. 

Meanwhile you should take up some newman or other related issues and work on fixing them.

Do assist other fellow students on the community to build their projects.

**Comment by adityaofficial10** [comment]
@Sharath-Postman 
Thanks a lot.
I have been working on Newman for 3 months now and I'll keep contributing to it.
I'll try help everyone who wants to get involved

**Comment by Sharath-Postman** [comment]
Mentors are looking into it and do create a new idea under discussions once you're ready

**Comment by adityaofficial10** [comment]
@Sharath-Postman 
This is to inform you that people are communicating by opening PRs directly in the newman repo, while my PR for the same was closed citing that it is a GSoC project.
Kindly look into this as this is unfair to the people who are using Forum and waiting patiently.

**Comment by Sharath-Postman** [comment]
@adityaofficial10 I think we are well aware of this and we will evaluate accordingly. 

As mentioned in the GSoC guidelines, one of the key points as part of the selection is community engagement and contribution. Therefore, I request you to focus on your project and take all the time and guidance you can get from the mentors to crystalize your idea in addition to your contributions.

Cheers

**Comment by adityaofficial10** [comment]
@Sharath-Postman 
Thanks for your assurance.. 
I appreciate this a lot.
This was just pre GSoC anxiety you know.😂🙏
