### ISSUE TITLE
Implementing parallel iterations

### ISSUE THREAD

**Issue by sambhavjai** [postmanlabs/gsoc#26]
Hi

I have compiled my proposal to implement parallel iterations in Newman for GSOC'21 in this document. 
Please review this document and share your valuable feedback. 
Waiting for your reply.

(https://docs.google.com/document/d/1BDPmUALcYlVCUCkNY88bSK8IVVnu6AlE1iVNU-JuGP0/edit?usp=sharing)

**Comment by Sharath-Postman** [comment]
@sambhavjai 
Thank you for submitting and we will look into this at the earliest but as mentioned in the guidelines on discourse, for your own benefit please discuss your idea on the discourse group with the mentors before going ahead and submitting your proposal directly here.

If you're still confident that this is your proposal, then request your patience.

Please don't tag anyone from postman while creating the issue. Request if you can update this one or create a new one, post reading the next line

Do let me know if you would like more time to discuss, get this reviewed with mentors on discourse.

**Comment by sambhavjai** [comment]
@Sharath-Postman thanks for the reply. I have removed the tags from the post and will discuss this approach on discourse first with the mentors. 
Thanks again.

**Comment by Sharath-Postman** [comment]
Thank you and welcome. Please discuss with the mentors on discourse and then create an idea under discussions in this repo (https://github.com/postmanlabs/gsoc/discussions) as mentioned in the guideline post freezing on your project proposal.

Cheers and best of luck
