### ISSUE TITLE
Can I get more details about Idea 6: Open API Postman Public Workspace?

### ISSUE THREAD

**Issue by rishipurwar1** [postmanlabs/gsoc#28]
Hello @abhijitkane @ankit-m @Sharath-Postman,
I am interested in **_Idea 6: Open API Postman Public Workspace_**. I have hands-on experience with Postman public workspace. During Postman API Hackathon, I made two public workspaces.
You can have a look at those public workspaces here:
[1. Twitter Bot](https://www.postman.com/thefierycoder/workspace/twitter-bot/overview)
[2. Smart Sharer](https://www.postman.com/thefierycoder/workspace/smart-sharer/overview)
I posted my query on [discourse](https://community.postman.com/t/can-i-get-more-details-about-idea-6-open-api-postman-public-workspace/21484/2) but I didn't get any response from the last 5 days.
Can any one of you give me more details on How to start contributing to the Postman Open API Public Workspaces?

_Note: I have gone through the idealist GSOC 2021 but there is very little information regarding idea 6._

Thank You

**Comment by Sharath-Postman** [comment]
Please check https://docs.google.com/document/d/1F2RWY7wmexsv5KOPsH7T_XiITt8gDK1PPPoaCFf5Ua8/edit#heading=h.xbhbuhcp6md1

or the Ideas list on github here - https://github.com/postmanlabs/gsoc/blob/master/2021/Ideas.md

More details will be added. by the mentor for this idea on our community channel later today

**Comment by rishipurwar1** [comment]
Thanks @Sharath-Postman
