### ISSUE TITLE
Need some more information regarding the Generation of Axios Code snippet

### ISSUE THREAD

**Issue by gp559** [postmanlabs/gsoc#4]
I use postman for my testing and modifying my api's for all the time and being a js developer i too feel that there should be code snippet for axios. But to start generation of axios snippet is please provide  some documentation about the generation process.

Thank you

**Comment by shreys7** [comment]
Hey @gp559, take a look at this contributing guide mentioned on the postman-code-generators repository.
https://github.com/postmanlabs/postman-code-generators/blob/develop/CONTRIBUTING.md
Feel free to comment if you need more help :)
