### ISSUE TITLE
"Support for more request body methods." whoch repo will give more idea about this? postman-collections or postman-runtime. 

### ISSUE THREAD

**Issue by pandyamarut** [postmanlabs/gsoc#8]
I want more understanding on how we are doing it for other request methods like OpenApI, GraphQl etc.
Also tried getting in touch with people on IRC. could not get through. 
Thank you in Advance!

**Comment by codenirvana** [comment]
Hey @pandyamarut,
These two modules are closely associated and changes are required at both the places.

The core of Postman is powered by Runtime that helps to execute requests and scripts and the Collection SDK allows to work with Postman Collection [schema](https://schema.getpostman.com/collection/json/v2.1.0/draft-07/docs/index.html) format.

Here are the PRs for adding support for GraphQL:
- https://github.com/postmanlabs/postman-collection/pull/843
- https://github.com/postmanlabs/postman-runtime/pull/800

**Comment by pandyamarut** [comment]
@codenirvana  Thanks. I will have a look. Might ping you back in case I'm stuck somewhere.

**Comment by pandyamarut** [comment]
@codenirvana  we go by handling the Request body first and then we add the respective mode right ?

**Comment by pandyamarut** [comment]
hi @codenirvana . If you have some time. Can I share one flow Which I understood with you to get reviews on it ?

**Comment by codenirvana** [comment]
@pandyamarut Sure.
